import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import {ShoppingCart} from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-secondary p-4 text-secondary-foreground">
          <div className="container mx-auto flex items-center justify-between">
            <Link href="/" className="text-lg font-bold">
              Ferraco Palmas
            </Link>
            <nav>
              <ul className="flex space-x-4">
                <li>
                  <Link href="/profile">Profile</Link>
                </li>
                <li>
                  <Link href="/cart" className="flex items-center">
                    <ShoppingCart className="mr-1" size={20} />
                    Cart
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="container mx-auto py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
